StudentInfo/StudentInfo/urls.py
import xadmin

from django.urls import path,include
# 上传图片
from django.conf import settings
from django.conf.urls.static import static

from users.views import LoginView,SingInView,LogoutView
from performance.views import StudentInfo,StudentScore
from performance.views import TeacherInfo,StudentsGrades,TeacherStudents,TeacherCheckScore

urlpatterns = [
    path('xadmin/', xadmin.site.urls, name="xadmin"),
    path('captcha/', include('captcha.urls')),  # 验证码
    path('ueditor/', include('DjangoUeditor.urls')),

    path('login/', LoginView.as_view(), name="login"),  # 登录
    path('sing_in/', SingInView.as_view(), name="sing_in"),  # 登录
    path('logout/',LogoutView.as_view(),name="logout"), #注销

    # performance/views
    # 学生
    path('student_info/', StudentInfo.as_view(), name="student_info"),  # 修改学生个人信息
    path('student_score/', StudentScore.as_view(), name="student_score"),  # 查看成绩
    # 教师
    path('teacher_info/', TeacherInfo.as_view(), name="teacher_info"),  # 个人信息
    path('grades/', StudentsGrades.as_view(), name="grades"),  # 班级列表
    path('teacher-students/', TeacherStudents.as_view(), name="teacher-students"),  # 班级列表
    path('teacher-check/', TeacherCheckScore.as_view(), name="teacher-check"),  # 教师查询学生成绩


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StudentInfo/extra/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

StudentInfo/apps/performance/models.py
from datetime import datetime

from django.db import models
from users.models import UserProfile as User

# Create your models here.


class Role(models.Model):
    name = models.CharField(max_length=15,default="", verbose_name="名称")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "角色"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Teacher(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True,verbose_name="用户")
    name = models.CharField(max_length=15,default="", verbose_name="教师名")
    sex = models.CharField(max_length=6,default='male', choices=(('male','男'), ('female','女')), verbose_name="性别")
    project = models.CharField(max_length=45,null=True,blank=True,verbose_name="专业")
    phone = models.CharField(max_length=11,null=True,blank=True,verbose_name="手机号码")
    college = models.CharField(max_length=45,null=True,blank=True,verbose_name="学院")
    # 角色，一个角色多个教师
    role = models.ForeignKey(Role,on_delete=models.CASCADE,null=True, blank=True,related_name="teachers", verbose_name="角色")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "教师"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Student(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,blank=True,verbose_name="用户")
    number = models.CharField(max_length=30, null=True,blank=True,verbose_name="学号")
    name = models.CharField(max_length=15, default="匿名", verbose_name="名称")
    sex = models.CharField(max_length=6, default='male', choices=(('male', '男'), ('female', '女')), verbose_name="性别")
    project = models.CharField(max_length=45, null=True, blank=True, verbose_name="专业")
    phone = models.CharField(max_length=11, null=True, blank=True, verbose_name="手机号码")
    college = models.CharField(max_length=45, null=True, blank=True, verbose_name="学院")
    grade = models.ForeignKey("Grade",on_delete=models.CASCADE,null=True, blank=True,related_name="students",verbose_name="班级")
    # 多个学生担任一个角色
    role = models.ForeignKey(Role, on_delete=models.CASCADE,null=True, blank=True, related_name="students", verbose_name="角色")

    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "学生"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 班级
class Grade(models.Model):
    # 一个老师多个班级；一个班级多个学生。
    name = models.CharField(max_length=15, default="", verbose_name="班级名")
    teacher = models.ForeignKey(Teacher,on_delete=models.CASCADE, related_name="grades", verbose_name="辅导员")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "班级"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 课程名
class Course(models.Model):
    name = models.CharField(max_length=15, default="", verbose_name="课程名")
    periods = models.CharField(max_length=30, null=True,blank=True,verbose_name="学时")
    credits = models.CharField(max_length=15, default="2",verbose_name="学分")
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE,related_name="courses", verbose_name="科任老师")

    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程名"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 班级课程表（课程表：软件一班的html课程）
class CourseGrade(models.Model):
    grade = models.ForeignKey(Grade,on_delete=models.CASCADE,related_name="course_grade",verbose_name="班级名")
    course = models.ForeignKey(Course,on_delete=models.CASCADE,related_name="course_grade",verbose_name="课程名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "班级课程表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{}{}".format(self.grade.name, self.course.name)


# 成绩类型
class PerformanceType(models.Model):
    name = models.CharField(max_length=30,default="", verbose_name="类型名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "成绩类型"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 成绩
class Performance(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE,related_name="performances",verbose_name="学号")
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="performances", verbose_name="课程")
    score_num = models.CharField(max_length=45, null=True,blank=True,verbose_name="成绩")
    type = models.ForeignKey(PerformanceType,related_name="performances",on_delete=models.CASCADE,verbose_name="类型名")
    term = models.CharField(max_length=15, default="one",choices=(("one","第一学期"),("two","第二学期")), verbose_name="学期")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")


    class Meta:
        verbose_name = "成绩"
        verbose_name_plural = verbose_name

    def __str__(self):
        return f"{self.student.number}的{self.course.name}的成绩为：{self.score_num}"

StudentInfo/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class UserProfile(AbstractUser):
    """ 用户扩展 """
    name = models.CharField(max_length=15,null=True,blank=True,verbose_name="姓名")  # 可以用手机号码和密码登录，不用名字
    birthday = models.DateField(null=True,blank=True,verbose_name="生日")
    gender = models.CharField(max_length=6,default='male', choices=(('male','男'), ('female','女')), verbose_name="性别")
    role = models.CharField(max_length=8,default='student', choices=(('student','学生'), ('teacher','老师')),verbose_name="职责")
    mobile = models.CharField(null=True,blank=True,max_length=11,verbose_name="手机号码")
    email = models.EmailField(max_length=100,null=True,blank=True,verbose_name="邮箱")

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name

    def __str__(self):
        if self.name:
            return self.name
        else:
            return self.username  # 父类AbstractUser原本的属性

StudentInfo/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

    {% block extends_head %}{% endblock %}

</head>
<body>
    <nav class="navbar navbar-default" style="background: #4ac1c1;">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

          <a class="navbar-brand" href="{% if request.user.role == "student" %}{% url 'student_info' %}{% elif request.user.role == "teacher" %}{% url 'teacher_info' %} {% endif %}">学生成绩管理系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
              {% if request.user.is_authenticated %}
                <li><a>{{ request.user.username }},欢迎你</a></li>
                <li><a href="{% url 'logout' %}?from={{ request.get_all_path }}">注销</a></li>
              {% else %}
                  <li><a href="{% url 'login' %}">登录</a></li>
                  <li><a href="{% url 'sing_in' %}">注册</a></li>
              {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


    {% block content %}{% endblock %}
    {% block js %}{% endblock %}
</body>
</html>

StudentInfo/templates/base_reg.html
{% extends 'base.html' %}
{% load static %}

{% block title %}学生信息管理系统{% endblock %}

{% block extends_head %}
    <style type="text/css">
        .regulateLi{
            list-style: none;
        }
        .regulateLi span{
            color: #555;
        }
        .active{
            background-color: #d9edf7;
            padding: 5px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <!-- 分类 -->
            <div class="hidden-xs col-sm-4 col-md-3 col-lg-3">

                {% if request.user.role == "student" %}
                    {# 学生管理 #}
                    <div class="left_form panel panel-default">
                        <div class="panel-heading"><strong>学生管理</strong></div>
                        <div class="panel-body">
                             <ul class="blog-types">
                                    <li class="regulateLi " >
                                        <span style="margin-right: 5px;" class="glyphicon glyphicon-th-large"></span>
                                        <a href="{% url 'student_score' %}"><span class="{% ifequal current_page "score" %}active{% endifequal %}">成绩查询</span></a>
                                    </li>
                                    <li class="regulateLi ">
                                        <span style="margin-right: 5px;" class="glyphicon glyphicon-th-large"></span>
                                        <a href="{% url 'student_info' %}"><span class="{% ifequal current_page "info" %}active{% endifequal %}">个人信息</span></a>
                                    </li>
                                </ul>
                         </div>
                    </div>
                {% elif request.user.role == "teacher" %}
                    {# 教师管理 #}
                    <div class="panel panel-default">
                        <div class="panel-heading"><strong>教师管理</strong></div>
                        <div class="panel-body">
                                <ul class="blog-types">
                                    {# 课程列表 #}
                                    <li class="regulateLi">
                                        <span style="margin-right: 5px;" class="glyphicon glyphicon-th-large"></span>
                                        <!-- Small button group -->
                                        <div class="btn-group">
                                          <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            课程列表 <span class="caret"></span>
                                          </button>
                                          <ul class="dropdown-menu">
                                              <li><a href="{% url 'grades' %}"><span class="{% ifequal current_page "grades" %}active{% endifequal %}">班级列表</span></a></li>
                                              <li><a href=""><span class="{% ifequal current_page "teacher_score_refer" %}active{% endifequal %}">成绩查询</span></a></li>
                                          </ul>
                                        </div>
                                    </li>
                                    {# 个人信息 #}
                                    <li class="regulateLi" style="margin-top: 5px;">
                                        <span style="margin-right: 5px;" class="glyphicon glyphicon-th-large"></span>
                                        <a href="{% url 'teacher_info' %}"><span class="{% ifequal current_page "teacher-info" %}active{% endifequal %}">个人信息</span></a>
                                    </li>
                                </ul>
                         </div>
                    </div>
                {% else %}
                    {# 身份不详 #}
                    <div class="left_form panel panel-default">
                        <div class="panel-heading"><strong>身份不详</strong></div>
                        <div class="panel-body">
                             <ul class="blog-types">
                                    <li class="regulateLi">
                                        <span style="margin-right: 5px;" class="glyphicon glyphicon-th-large"></span>
                                        <a href="{% url 'login' %}">身份不详</a>
                                    </li>
                                </ul>
                         </div>
                    </div>
                {% endif %}
            </div>

            <!-- 列表 -->
            <div class="col-sm-8 col-md-9 col-lg-9">
                {% block right_form %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

StudentInfo/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}登录{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="panel panel-default">
                  <div class="panel-body">
                      <div style="background-color: #4ac1c1;">
                          <h3 class="panel-title"style="padding: 20px;color: #fff;">{{ placard }}</h3>
                      </div>
                  </div>
                </div>
            </div>
        </div>
        </div>
    {% else %}
    {# 登录界面 #}
    <div class="body">
        <div class="panel panel-default" style="width: 500px;margin: 0 auto;margin-top: 50px;">
          <div class="panel-heading" style=" background:#4ac1c1;">登录</div>
          <div class="panel-body">
            <form action="{% url 'login' %}" method="POST">
                {% csrf_token %}
              {# 用户名 #}
              <div class="form-group">
                <label for="exampleInputEmail1">用户名</label>
                <input type="text" name="username" class="form-control" value="{{ login_form.username.value }}" id="username" placeholder="用户名">
              </div>
             {# 密码 #}
              <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input type="password" name="password" class="form-control" value="{{ login_form.password.value }}" id="password" placeholder="密码">
              </div>
            {# 身份 #}
            <div class="form-group">
                <label class="radio-inline">
{#                    {{ user.get_role_display }}#}
                  <input type="radio" checked  name="role" id="inlineRadio1" value="student">学生
                </label>
                <label class="radio-inline">
                  <input type="radio" name="role" id="inlineRadio2" value="teacher">老师
                </label>
            </div>
               <button type="submit" class="btn btn-default" style=" background:#4ac1c1;float: right;">登录</button>
            </form>
              <div class="error">
                  {% for k,v in login_form.errors.items %}
                      {{ v }}
                  {% endfor %}
                {{ msg }}
              </div>
          </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

StudentInfo/templates/reg-homepage.html
{% extends 'base_reg.html' %}


{% block right_form %}
    {# 内容 #}
        <h1>欢迎你：{{ request.user.username }}</h1>
   {# 分页 #}
    <nav aria-label="Page navigation" style="text-align: center;">
      <ul class="pagination">
        <li>
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li>
          <a href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>

{% endblock %}

StudentInfo/templates/reg-student-info.html
{% extends 'base_reg.html' %}

{% block title %}学生个人信息{% endblock %}
{% if student %}
{% block right_form %}
     {# 个人信息 #}
    <form class="form-horizontal">
      <div class="form-group">
        <label for="inputname" class="col-sm-2 control-label">名字</label>
        <div class="col-sm-10">
          <input type="text" name="name" class="form-control" id="inputname" value="{{ student.name }}">
        </div>
      </div>

      <div class="form-group">
          <label class="col-sm-2 control-label">性别</label>
          <div class="col-sm-10">
               <select id="select1" class="form-control" name="sex">
                  <option value="male">男</option>
                  <option value="female">女</option>
                </select>
          </div>
      </div>

      <div class="form-group">
        <label for="inputphone" class="col-sm-2 control-label">手机号码</label>
        <div class="col-sm-10">
          <input type="number" name="phone" class="form-control" id="inputphone" value="{{ student.phone }}">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="button" class="btn btn-default" onclick="update_info({{ student.pk }})">修改</button>
        </div>
      </div>
    </form>
{% endblock %}

{% block js %}
    <script type="text/javascript">
    // 设置select1默认值
    $('#select1 option[value="{{ student.sex }}"]').attr("selected", "selected");


        function update_info(student_pk) {
            var name = $("input[name='name']").val();
            var sex = $("option:selected").val();
            var phone = $("input[name='phone']").val();
            {#console.log(name,sex,phone);#}
            var data = {
                "student_pk": student_pk,
                "ipt_name": name,
                "ipt_sex": sex,
                "ipt_phone": phone,
            };

            $.ajax({
                cache: false,
                type: "POST",
                url:"{% url 'student_info' %}",
                data: data,
                async: true,
                beforeSend:function(xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function(data) {
                    location.reload(true);  // 刷新页面
                    alert(data.msg);  // 提示
                },
                // 错误
                fail:function (data) {
                    alert(data.msg);
                }
            });
        }
    </script>
{% endblock %}
{% endif %}

StudentInfo/templates/reg-student-score.html
{% extends 'base_reg.html' %}

{% block title %}学生成绩{% endblock %}

{% block right_form %}
{% if performs %}
<table class="table table-hover">
      <thead>
        <tr>
            <th>#</th>
            <th>课程</th>
            <th>成绩</th>
            <th>类型</th>
            <th>学期</th>
        </tr>
      </thead>
      <tbody>

        {% for perform in performs.object_list %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{ perform.course.name }}</td>
                <td>{{ perform.score_num }}</td>
                <td>{{ perform.type.name }}</td>
                <td>{{ perform.term }}</td>
            </tr>
        {% endfor %}

      </tbody>
    </table>

    {# 分页 #}
    <nav aria-label="Page navigation" style="text-align: center;">
      <ul class="pagination">
      {% if performs.has_previous %}
          <li>
              <a href="?{{ performs.previous_page_number.querystring }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
          </li>
      {% endif %}
        {% for page in performs.pages %}
            {% if page %}
                {# 如果是当前页面 #}
                {% ifequal page all_blog.number %}
                    <li class="active"><a href="#">{{ page }}</a></li>

                {# 如果是当前页面end #}
                {# 如果不是当前页面 #}
                {% else %}
                    <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                {% endifequal %}
                {# 如果不是当前页面end #}
            {% else %}
                ...
            {% endif %}
        {% endfor %}

  {% if all_blog.has_next %}
        <li>
          <a href="?{{ all_blog.next_page_number.querystring }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
  {% endif %}
  </ul>
    </nav>

{% else %}
    <p>暂无成绩！</p>
{% endif %}
{% endblock %}

StudentInfo/templates/sign.html
{% extends 'base.html' %}
{% load static %}

{% block title %}注册{% endblock %}

{% block content %}
    {# 登录界面 #}
    <div class="body">
        <div class="panel panel-default" style="width: 500px;margin: 0 auto;margin-top: 50px;">
          <div class="panel-heading" style=" background:#4ac1c1;">注册</div>
          <div class="panel-body">
            <form action="{% url 'sing_in' %}" method="POST">
                {% csrf_token %}
              {# 用户名 #}
              <div class="form-group">
                <label for="exampleInputEmail1">用户名</label>
                <input type="text" name="username" class="form-control" value="{{ register_form.username.value }}" id="username" placeholder="用户名">
              </div>
              {# 邮箱 #}
              <div class="form-group">
                <label for="exampleInputEmail1">邮箱</label>
                <input type="email" name="email" class="form-control" value="{{ register_form.email.value }}" id="email" placeholder="邮箱">
              </div>
             {# 密码 #}
              <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input type="password" name="password" class="form-control" value="{{ register_form.password.value }}" id="password" placeholder="密码">
              </div>
             {# 确认密码 #}
              <div class="form-group">
                <label for="exampleInputPassword1">确认密码</label>
                <input type="password" name="password_again" class="form-control" value="{{ register_form.password_again.value }}" id="password" placeholder="确认密码">
              </div>

            {# 身份 #}
            <div class="form-group">
                <label class="radio-inline">
{#                    {{ user.get_role_display }}#}
                  <input type="radio" checked  name="role" id="inlineRadio1" value="student">学生
                </label>
                <label class="radio-inline">
                  <input type="radio" name="role" id="inlineRadio2" value="teacher">老师
                </label>
            </div>
            {# 验证码 #}
            <div class="form-group">
                {{register_form.captcha}}
            </div>
               <button type="submit" class="btn btn-default" style=" background:#4ac1c1;float: right;">注册</button>
            </form>
              <div class="error">
                  {% for k,v in register_form.errors.items %}
                      {{ v }}
                  {% endfor %}
                {{ msg }}
              </div>
          </div>
        </div>
    </div>
<script type="text/javascript">
        //验证码刷新
         $(function(){
            $("img.captcha").click(function(){   //更新验证码图片ajax
                $.getJSON("/captcha/refresh",function(data){
                    $("img.captcha").attr("src",data.image_url);
                    $("#id_captcha_0").attr("value",data.key);
                });
            });
        });

    </script>
{% endblock %}

StudentInfo/templates/teacher-check.html
{% extends 'base_reg.html' %}

{% block title %}{{ student.name }}的成绩{% endblock %}

{% block right_form %}
<div class="panel panel-info">
  <div class="panel-body">
    <div style="text-align: center;">{{ student.name }}的成绩</div>
  </div>
</div>
<table class="table table-hover">
      <thead>
        <tr>
            <th>#</th>
            <th>课程</th>
            <th>成绩</th>
            <th>类型</th>
            <th>学期</th>
        </tr>
      </thead>
      <tbody>

        {% for perform in performs %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{ perform.course.name }}</td>
                <td>{{ perform.score_num }}</td>
                <td>{{ perform.type.name }}</td>
                <td>{{ perform.get_term_display }}</td>
            </tr>
        {% endfor %}

      </tbody>
    </table>

{% endblock %}

StudentInfo/templates/teacher-grades.html
{% extends 'base_reg.html' %}

{% block title %}班级列表{% endblock %}

{% block right_form %}
    <div class="list-group">
        {% for grade in grades %}
            <a href="{% url 'teacher-students' %}?grade_pk={{ grade.pk }}&teacher_pk={{ teacher.pk }}" class="list-group-item">{{ grade.name }}</a>
        {% empty %}
            <a class="list-group-item">暂无班级</a>
        {% endfor %}

    </div>
{% endblock %}

StudentInfo/templates/teacher-info.html
{% extends 'base_reg.html' %}

{% block title %}教师个人信息{% endblock %}

{% block right_form %}
     {# 个人信息 #}
    <form class="form-horizontal">
      <div class="form-group">
        <label for="inputname" class="col-sm-2 control-label">名字</label>
        <div class="col-sm-10">
          <input type="text" name="name" class="form-control" id="inputname" value="{{ teacher.name }}">
        </div>
      </div>

      <div class="form-group">
          <label class="col-sm-2 control-label">性别</label>
          <div class="col-sm-10">
               <select id="select1" class="form-control" name="sex">
                  <option value="male">男</option>
                  <option value="female">女</option>
                </select>
          </div>
      </div>

      <div class="form-group">
        <label for="inputphone" class="col-sm-2 control-label">手机号码</label>
        <div class="col-sm-10">
          <input type="number" name="phone" class="form-control" id="inputphone" value="{{ teacher.phone }}">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="button" class="btn btn-default" onclick="update_info({{ teacher.pk }})">修改</button>
        </div>
      </div>
    </form>
{% endblock %}

{% block js %}
    <script type="text/javascript">
    // 设置select1默认值
    $('#select1 option[value="{{ teacher.sex }}"]').attr("selected", "selected");


        function update_info(teacher_pk) {
            var name = $("input[name='name']").val();
            var sex = $("option:selected").val();
            var phone = $("input[name='phone']").val();
            {#console.log(name,sex,phone);#}
            var data = {
                "teacher_pk": teacher_pk,
                "ipt_name": name,
                "ipt_sex": sex,
                "ipt_phone": phone,
            };

            $.ajax({
                cache: false,
                type: "POST",
                url:"{% url 'teacher_info' %}",
                data: data,
                async: true,
                beforeSend:function(xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function(data) {
                    location.reload(true);  // 刷新页面
                    alert(data.msg);  // 提示
                },
                // 错误
                fail:function (data) {
                    alert(data.msg);
                }
            });
        }
    </script>
{% endblock %}